app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,FileField,TextAreaField, SelectField
from wtforms.validators import DataRequired, Length, ValidationError, EqualTo, Email, Regexp
from app.models import User, Tag

tags = Tag.query.all()


class LoginForm(FlaskForm):
    account = StringField(
        label="账号",
        validators=[
            DataRequired("用户名不能为空"),
        ],
        description="账号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号",
            # "required": "required"
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired(message="请输入密码!")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码!",
            # "required": "required"
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "user_login_btn"
        }
    )

    def validate_account(self, field):
        account = field.data
        id = User.query.filter_by(id=account).count()
        if id == 0:
            raise ValidationError("账号不存在！")


class RegistForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称!")
        ],
        description="昵称",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入昵称",
        }
    )

    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired(message="请输入密码!")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "id": "pw1",
            "placeholder": "请输入密码!",
        }
    )

    repwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired(message="确认密码!"),
            EqualTo("pwd", message="两次密码不一致")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control",
            "id": "pw2",
            "placeholder": "确认密码!",
        }
    )

    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱!"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号!"),
            Regexp("1[0-9]{10}", message="手机格式不正确")

        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号",
        }
    )

    submit = SubmitField(
        '注册',
        render_kw={
            "class": "regist_btn"
        }
    )


    def validate_name(self,field):
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError("昵称已经存在")
    def validate_email(self,field):
        email = field.data
        email = User.query.filter_by(email=email).count()
        if email == 1:
            raise ValidationError("邮箱已经存在")

    def validate_phone(self, field):
            phone = field.data
            phone = User.query.filter_by(phone=phone).count()
            if phone == 1:
                raise ValidationError("手机已经存在")

class UserdetailForm(FlaskForm):
    name = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称!")
        ],
        description="昵称",
        render_kw={
            "class": "personal_name_change",
            "placeholder": "请输入昵称",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱!"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "personal_email_change",
            "placeholder": "请输入邮箱",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号!"),
            Regexp("1[0-9]{10}", message="手机格式不正确")

        ],
        description="手机",
        render_kw={
            "class": "personal_phone_change",
            "placeholder": "请输入手机号",
        }
    )
    face = FileField(
        label="头像",
        validators=[
        ],
        description="头像",
        render_kw={
            "id":"face_change",
            "onchange":"handleFiles(this,'icon')"
        }
    )
    info = TextAreaField(
        label="个人介绍",
        validators=[
        ],
        description="简介",
        render_kw={
            "id":"personal_introduce_text_control",
            "maxlength":"80",
            "placeholder":"个人介绍",
            "rows":"5",
            "cols":"50"
        }
    )
    submit = SubmitField(
        '修改',
        render_kw={
            "class": "personal-info-change"
        }
    )

class PasswordChangeForm(FlaskForm):
    oldpwd = PasswordField(
        label="密码",
        validators=[
            DataRequired(message="请输入旧密码!")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "id": "pw_check",
            "placeholder": "旧密码!",
        }
    )

    newpwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired(message="请输入新密码"),
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "id": "pw_new",
            "placeholder": "新密码",
        }
    )
    submit = SubmitField(
        '确认密码',
        render_kw={
            "class": "personal-info-change"
        }
    )

class MovieForm(FlaskForm):
    title = StringField(
        label="视频标题",
        validators=[
            DataRequired("请输入视频标题")
        ],
        description="视频标题",
        render_kw={
            "class": "personal_name_change",
            "id":"movie_title",
            "placeholder": "请输入标题",
        }
    )
    url = FileField(
        validators=[
            DataRequired("请上传文件")
        ],
        description="视频"
    )
    logo = FileField(
        label="封面",
        validators=[
        ],
        description="封面",
        render_kw={
            "id": "logo_change",
            "onchange": "handleFiles(this,'icon')"
        }
    )
    tag = SelectField(
        label="标签",
        validators=[
            DataRequired("请选择标签")
        ],
        coerce=int,
        choices=[(v.id, v.name) for v in tags],
        description="标签",

    )
    submit = SubmitField(
        '上传',
        render_kw={
            "class": "movie_submit"
        }
    )

class CommentForm(FlaskForm):
    comment = TextAreaField(
        label="评论",
        validators=[
            DataRequired("评论不能为空")
        ],
        description="评论",
        render_kw={
            "id": "personal_comment_text_control",
            "maxlength": "80",
            "placeholder": "评论",
            "rows": "5",
            "cols": "50"
        }
    )
    submit = SubmitField(
        '提交',
        render_kw={
            "class": "personal-info-change"
        }
    )

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
from . import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from app.home.forms import LoginForm, RegistForm, UserdetailForm, PasswordChangeForm, MovieForm, CommentForm
from app.models import User, Movie, Tag, Likes, Moviecol, Comment
from functools import wraps
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from app import db, app, rd
import uuid
import os
import datetime


def user_login_req(fun):
    @wraps(fun)
    def decorated_function(*args, **kwargs):
        if "id" not in session:
            return redirect(url_for("home.login", next=request.url))
        return fun(*args, **kwargs)

    return decorated_function


def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


@home.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(id=data["account"]).first()
        if not user.check_pwd(data["pwd"]):
            flash("密码错误")
            return redirect(url_for("home.login"))
        session["id"] = user.id
        session["user_id"] = user.id
        return redirect(request.args.get("next") or url_for("home.user"))
    return render_template("home/login.html", form=form)


@home.route("/logout/")
def logout():
    session.pop("id", None)
    return redirect(url_for('home.index', page=1))


@home.route("/regist/", methods=["GET", "POST"])
def regist():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data["name"],
            email=data["email"],
            phone=data["phone"],
            pwd=generate_password_hash(data["pwd"]),
            uuid=uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        return render_template("home/registed.html", id=user.id)
    return render_template("home/regist.html", form=form)


@home.route("/registed/")
def registed():
    return render_template("home/registed.html")


@home.route("/user/", methods=["POST", "GET"])
@user_login_req
def user():
    form = UserdetailForm()
    user = User.query.get(int(session["user_id"]))
    form.face.validators = []
    if request.method == "GET":
        form.name.data = user.name
        form.phone.data = user.phone
        form.email.data = user.email
        form.info.data = user.info
        form.face.data = user.face
    if form.validate_on_submit():
        data = form.data
        if form.face.data:
            file_face = secure_filename(form.face.data.filename)
            if not os.path.exists(app.config["FC_DIR"]):
                os.makedirs(app.config["FC_DIR"])
                os.chmod(app.config["FC_DIR"], "rw")
            user.face = change_filename(file_face)
            form.face.data.save(app.config["FC_DIR"] + user.face)

        name_count = User.query.filter_by(name=data["name"]).count()
        if data["name"] != user.name and name_count == 1:
            flash("昵称重复", "err")
            return redirect(url_for("home.user"))

        phone_count = User.query.filter_by(phone=data["phone"]).count()
        if data["phone"] != user.phone and phone_count == 1:
            flash("电话重复", "err")
            return redirect(url_for("home.user"))

        email_count = User.query.filter_by(email=data["email"]).count()
        if data["email"] != user.email and email_count == 1:
            flash("邮箱重复", "err")
            return redirect(url_for("home.user"))

        user.name = data["name"]
        user.email = data["email"]
        user.phone = data["phone"]
        user.info = data["info"]
        db.session.add(user)
        db.session.commit()
        flash("修改成功", "ok")
        return redirect(url_for("home.user"))

    return render_template("home/user.html", form=form, user=user)


@home.route("/mymovie/<int:page>/", methods=["GET"])
@user_login_req
def mymovie(page=None):
    if page is None:
        page = 1
    user = User.query.get(int(session["user_id"]))
    movie = Movie.query.filter_by(author=user.name)
    page_data = movie.order_by(
        Movie.addtime.desc()
    ).paginate(page=page, per_page=10)
    tag = Tag
    return render_template("home/mymovie.html", page_data=page_data, tag=tag)


@home.route("/mymovie/add/", methods=["GET", "POST"])
@user_login_req
def movie_add():
    form = MovieForm()
    user = User.query.get(int(session["user_id"]))
    if form.validate_on_submit():
        data = form.data
        file_url = secure_filename(form.url.data.filename)
        file_logo = secure_filename(form.url.data.filename)
        if not os.path.exists(app.config["UP_DIR"]):
            os.makedirs(app.config["UP_DIR"])
            os.chmod(app.config["UP_DIR"], "rw")
        url = change_filename(file_url)
        logo = change_filename(file_logo)
        form.url.data.save(app.config["UP_DIR"] + url)
        form.logo.data.save(app.config["UP_DIR"] + logo)
        movie = Movie(
            title=data["title"],
            url=url,
            logo=logo,
            playnum=0,
            commentnum=0,
            author=user.name,
            tag_id=int(data["tag"]),
        )
        db.session.add(movie)
        db.session.commit()
        flash("添加成功", "ok")
        return redirect(url_for('home.movie_add'))

    return render_template("home/movie_add.html", form=form)


@home.route("/mymovie/del/<int:id>/", methods=["GET"])
@user_login_req
def movie_del(id=None):
    movie = Movie.query.filter_by(id=id).first_or_404()
    db.session.delete(movie)
    db.session.commit()
    flash("删除成功", "ok")
    return redirect(url_for("home.mymovie", page=1))


@home.route("/pwd/", methods=["GET", "POST"])
@user_login_req
def pwd():
    form = PasswordChangeForm()
    user = User.query.get(int(session["user_id"]))
    if form.validate_on_submit():
        data = form.data
        if not user.check_pwd(data["oldpwd"]):
            flash("密码错误")
            return redirect(url_for("home.pwd"))
        user.pwd = generate_password_hash(data["newpwd"])
        db.session.add(user)
        db.session.commit()
        flash("修改成功")
        return redirect(url_for("home.pwd"))

    return render_template("home/pwd.html", form=form)


@home.route("/comments/<int:page>/", methods=["GET"])
@user_login_req
def comments(page=None):
    if page is None:
        page = 1
    user = User.query.get(int(session["user_id"]))
    comments = Comment.query.filter_by(user_id=user.id)

    page_data = comments.order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=10)
    tag = Tag
    movie = Movie
    return render_template("home/comments.html", page_data=page_data, tag=tag, comments=comments,
                           movie=movie)


@home.route("/comments/del/<int:id>/", methods=["GET"])
@user_login_req
def comments_del(id=None):
    comments = Comment.query.filter_by(id=id).first_or_404()
    db.session.delete(comments)
    db.session.commit()
    flash("删除成功", "ok")
    return redirect(url_for("home.comments", page=1))


@home.route("/moviecol/add/", methods=["GET"])
@user_login_req
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    moviecol = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if moviecol == 1:
        data = dict(ok=0)
    else:
        moviecol = Moviecol(
            user_id=int(uid),
            movie_id=int(mid)
        )
        data = dict(ok=1)
        db.session.add(moviecol)
        db.session.commit()
    import json
    return json.dumps(data)


@home.route("/moviecol/<int:page>/", methods=["GET"])
@user_login_req
def moviecol(page=None):
    if page is None:
        page = 1
    user = User.query.get(int(session["user_id"]))

    page_data = Moviecol.query.filter(
        User.id == session["user_id"]
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template("home/moviecol.html", page_data=page_data)


@home.route("/moviecol/del/<int:id>/", methods=["GET"])
@user_login_req
def moviecol_del(id=None):
    moviecol = Moviecol.query.filter_by(id=id).first_or_404()
    db.session.delete(moviecol)
    db.session.commit()
    flash("删除成功", "ok")
    return redirect(url_for("home.moviecol", page=1))


@home.route("/like/add/", methods=["GET"])
@user_login_req
def like_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    like = Likes.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if like == 1:
        data = dict(ok=0)
    else:
        like = Likes(
            user_id=int(uid),
            movie_id=int(mid)
        )
        data = dict(ok=1)
        db.session.add(like)
        db.session.commit()
    import json
    return json.dumps(data)


# @home.route("/tm/", methods=["GET", "POST"])
# def tm():
#     import json
#     if request.method == "GET":
#         id = request.args.get("id")
#         key = "movie" + str(id)
#         if rd.llen(key):
#             msgs = rd.lrange(key, 0, 2999)
#             res = {
#                 "code": 1,
#                 "danmaku": [json.loads(v) for v in msgs]
#             }
#         else:
#             res = {
#                 "code": 1,
#                 "danmaku": []
#             }
#         resp = json.dumps(res)
#     if request.method == "POST":
#         data = json.loads(request.get_data())
#         msg = {
#             "__v": 0,
#             "author": data["author"],
#             "time": data["time"],
#             "text": data["text"],
#             "color": data["color"],
#             "type": data["type"],
#             "ip": request.remote_addr,
#             "_id": datetime.datetime.now().strftime("%Y%m%d%H%M%S") + uuid.uuid4().hex,

app/templates/home/home.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>司母戊鼎</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/hometop.css') }}" charset="utf-8">
    <style>
        html, body {
            width: 100%;
            height: 100%;
        }

        body {
            background: url("{{ url_for('static',filename='base/images/home.jpg') }}") bottom center no-repeat;
            background-size: 100% 100%;
            width: 100%;
            height: 100%;

        }

        .headpic > a > img {
            position: absolute;
            top: 56px;
            margin-left: 50px;
            height: 70px;
            width: 70px;
        }

        .headlink > ul {
            display: flex;
            margin-left: 25%;
            list-style: none;
            justify-content: center;
            text-align: left;
            font-size: large;
            padding-top: 70px;
        }

        .curlink {
            display: flex;
            text-decoration: none;
            color: black;
            margin: 10px 40px;
            font-weight: bold;
            background-color: #c4e0e4;
            border-radius: 10px;
            width: 80px;
            justify-content: center;
        }


    </style>
    <!--外观-->
    {% block css %}
    {% endblock %}
    <!--外观-->
</head>
<body>
<!--导航-->

<div class="headlink">
    <div class="headpic">
        <a href="{{ url_for('home.index',page=1) }}">
            <img src="{{ url_for('static',filename='base/images/logo.png') }}">
        </a>
    </div>
    <ul>
        <li><a class="curlink" href="{{ url_for('home.user') }}"><span class="curlinksty"></span>个人中心</a></li>
        <li><a class="curlink" href="{{ url_for('home.login') }}"><span class="curlinksty"></span>登录</a></li>
        <li><a class="curlink" href="{{ url_for('home.regist') }}"><span class="curlinksty"></span>注册</a></li>
        <li><a class="curlink" href="{{ url_for('home.logout') }}"><span class="curlinksty"></span>退出</a></li>
    </ul>
</div>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:100px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/loginlog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% import "ul/admin_page.html" as pg %}
{% block css %}
<style>
    .user_sq {
        display: flex;
        height: 80%;
        width: 70%;
        margin: 0 15% 0 15%;
        background: white;
    }

    .menu_curlink {
        text-decoration: none;
        background-color: white;
        color: black;
    }

    .menu {

        padding-right: 70px;
    }

    .menu_curlink > span {
        display: flex;
        padding-top: 20px;
        padding-bottom: 20px;
        justify-content: center;
        text-align: center;
        width: 200px;
        font-weight: bold;
        font-size: larger;
        background-color: #c4e0e4;
    }


    #user_con_head{
        display: flex;
        justify-content: center;
        text-align: center;
        width: 500px;
    }
    .table-table-hover>tbody>tr>th{
        width: 200px;
    }
    .table-table-hover>tbody>tr>td{
        width: 200px;
        text-align: center;
    }
    .box-footer-clearfix>ul{
        display: flex;
        justify-content: right;
        text-align: right;
        list-style: none;
        justify-content: center;
        text-align: center;
    }
    .box-footer-clearfix>ul>li>a{
        text-decoration: none;
        color: #ba2bcc;
    }
    .user_sq_flash {
        display: flex;
        justify-content: center;
        text-align: center;
        color: red;
        background: white;
        font-size: larger;
        font-weight: bold;
        margin-left: 15%;
        width: 70%;
    }
    .add_movie{
        text-align: center;
        color: orange;
        font-size: large;
        font-weight: bold;
        margin-bottom: 20px;

    }
    .add_movie_link{
        text-decoration: none;


    }
    .add_movie_link>span{
        text-align: center;
        background: #34ff52;
    }
</style>
{% endblock %}

{% block content %}
        {% for msg in get_flashed_messages() %}
        <p class="user_sq_flash" >{{ msg }}</p>
        {% endfor %}
<div class="user_sq">
    {% include "home/menu.html" %}
    <div id="user_con">
        <div id="user_con_head">
            <h2 class="user_con_head_text">收藏管理</h2>
        </div>
        <div class="box-body table-responsive no-padding">
                            <table class="table-table-hover">
                                <tbody>
                                <tr>
                                    <th>编号</th>
                                    <th>名称</th>
                                    <th>添加时间</th>
                                    <th>操作事项</th>
                                </tr>
                                {% for v in page_data.items %}
                                <tr>
                                    <td>{{ v.id }}</td>
                                    <td>{{ v.movie.title }}</td>
                                    <td>{{ v.addtime }}</td>
                                    <td>
                                        <a class="label label-danger" href="{{ url_for('home.play',id=v.id,page=1) }}">查看</a>
                                        <a class="label label-danger" href="{{ url_for('home.moviecol_del',id=v.id) }}">删除</a>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer-clearfix">
                            {{ pg.page(page_data,'home.moviecol') }}
                        </div>

    </div>

</div>
{% endblock %}

app/templates/home/play.html
{% extends "home/home.html" %}
{% import "ul/comment_page.html" as pg %}
{% block css %}

<link rel="stylesheet" href="{{ url_for('static',filename='dplayer/dist/Dplayer.min.css') }}" >
<script src="{{ url_for('static',filename='dplayer/dist/DPlayer.min.js') }}"></script>

<style>
    .box-footer-clearfix > ul {
        display: flex;
        justify-content: right;
        text-align: right;
        list-style: none;
        justify-content: center;
        text-align: center;
    }

    .box-footer-clearfix > ul > li > a {
        text-decoration: none;
        color: indigo;
    }

    .form-control-personal {
        display: flex;
        justify-content: center;
        text-align: center;
        margin-bottom: 30px;

    }

    #dplayer {

        size: auto;
    }

    .user_sq {

        height: 80%;
        width: 70%;
        margin: 0 15% 0 15%;
        background: white;
    }

    .play_head {
        font-weight: bold;
        font-size: xx-large;
        color: #ba2bcc;
        text-align: center;
    }

    #play {
        display: flex;
        justify-content: center;
        text-align: center;
    }

    #play_love > a {
        text-decoration: none;
        font-size: larger;
        font-weight: bold;
        color: orange;
    }

    #play_col > a {
        text-decoration: none;
        font-size: larger;
        font-weight: bold;
        color: orange;
    }

    .user_sq_flash {
        display: flex;
        justify-content: center;
        text-align: center;
        color: red;
        background: white;
        font-size: larger;
        font-weight: bold;
        margin-left: 15%;
        width: 70%;
    }

    .personal_introduce_text {
        display: flex;
        justify-content: center;
        text-align: center;
    }

    .personal-info-change {
        width: 70px;
        height: 35px;
        font-weight: bold;
        margin-right: 30px;
        color: white;
        background-color: forestgreen;
        border-radius: 30px;
        font-size: large;
        font-style: oblique;
    }

    .personal_introduce_show > span {
        display: flex;
        justify-content: center;
        text-align: center;
        font-size: 30px;
        font-weight: bold;
        color: orange;
    }

    #comment_get {
        background: #c9cc4d;
    }

    #play_comments {
        margin-bottom: 30px;
        padding-bottom: 30px;
        padding-left: 40px;
        background: lightblue;

    }

    .comment_name_show {
        width: 100px;
        text-align: center;
        color: red;
    }

    #comment_name_show_head {
        color: indigo;
        font-size: 20px;
        margin-bottom: 5px;
    }

    #comment_content_show_head {
        color: indigo;
        font-size: 20px;
        margin-bottom: 5px;
    }

    #play_num_text {
        font-size: large;
        color: red;
    }

    #play_num_data {
        font-size: medium;
        color: #ba2bcc;
    }

    .play_con_btn {
        display:;
    }
    #col_msg{
        font-size: 10px;
        font-weight: bold;
    }
    #like_msg{
        font-size: 10px;
        font-weight: bold;
    }
</style>
{% endblock %}


{% block content %}
{% for msg in get_flashed_messages() %}
<p class="user_sq_flash">{{ msg }}</p>
{% endfor %}
<div class="user_sq">

    <div class="play_head">{{ movie.title }}</div>
    <div class="paly_num"><span id="play_num_text">播放量：</span><span id="play_num_data">{{ movie.playnum }}</span></div>
    <div id="play">
        <div id="dplayer"></div>
    </div>
    <div class="play_info">
        <div id="play_love">
            <a  id="play_like_btn" class="play_con_btn">点赞</a>
            <span>{{ like }}</span>
            <div><span id="like_msg"></span></div>
        </div>
        <div id="play_col">
            <a id="play_col_btn" class="play_con_btn">收藏</a>
            <span>{{ col }}</span>
            <div><span id="col_msg"></span></div>
        </div>
    </div>
    <div id="comments_get">
        {% if "id" not in session %}
        <div id="comment_warn">
            <span class="comment_login_warn">请</span>
            <a href="{{ url_for('home.login') }}" id="comment_login">登录</a>
            <span class="comment_login_warn">再评论</span>
        </div>
        {% endif %}
        {% if "id" in session %}
        <div id="comment_get">
            <form method="POST" id="form-comments-get" enctype="multipart/form-data">
                <div class="personal_introduce_show">
                    <span>评论</span>
                    <div class="personal_introduce_text">
                        {{ form.comment }}
                    </div>
                </div>
                <div class="form-control-personal">
                    {{ form.csrf_token }}
                    {{ form.submit }}
                </div>
            </form>
        </div>
        {% endif %}
    </div>
    <div id="play_comments">
        <div class="comments_sq">
            <div class="box-body table-responsive no-padding">
                <table class="table-table-hover">
                    <tbody>
                    <tr>
                        <th class="comment_name_show" id="comment_name_show_head">昵称</th>
                        <th class="comment_content_show" id="comment_content_show_head">内容</th>
                    </tr>
                    {% for v in page_data.items %}
                    <tr>
                        <td class="comment_name_show">{{ users.query.get(v.user_id).name }}</td>
                        <td class="comment_content_show">{{ v.content }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>


            </tbody>
            </table>
        </div>
        <div class="box-footer-clearfix">
            {{ pg.page(page_data,'home.play',movie.id) }}
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script src="https://cdn.jsdelivr.net/npm/dplayer@1.25.0/dist/DPlayer.min.js"></script>

<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.js"></script>
<script>

        var dp1 = new DPlayer({
            container: document.getElementById('dplayer'),
            video: {
                url: "{{ url_for('static', filename='uploads/'+'movie'+movie.url) }}"
            },
            danmaku: {
                id: '{{ movie.id }}',
                api: "/tm/"
            }
        });
</script>


<script type="text/javascript">
    $(document).ready(function () {
        $("#play_col_btn").click(function () {
            var mid = {{ movie.id }};
            var uid = {{ session['user_id'] }};
            $.ajax({
                url:"{{ url_for('home.moviecol_add') }}",
                type:"GET",
                dataType:"json",
                data:"mid=" + mid + "&uid=" + uid,
                success:function (res) {
                    if(res.ok==1){
                        $("#col_msg").empty();
                        $("#col_msg").append("收藏成功！");
                    }else{
                        $("#col_msg").empty();
                        $("#col_msg").append("已收藏！");
                    }
                }
            })
        })
    })
    $(document).ready(function () {
        $("#play_like_btn").click(function () {
            var mid = {{ movie.id }};
            var uid = {{ session['user_id'] }};
            $.ajax({
                url:"{{ url_for('home.like_add') }}",
                type:"GET",
                dataType:"json",
                data:"mid=" + mid + "&uid=" + uid,
                success:function (res) {
                    if(res.ok==1){
                        $("#like_msg").empty();
                        $("#like_msg").append("点赞成功！");
                    }else{
                        $("#like_msg").empty();
                        $("#like_msg").append("已点赞！");
                    }
                }
            })
        })
    })
</script>
{% endblock %}